# Generated by Django 3.2.16 on 2022-12-14 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0005_myowntoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='toDo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Id')),
                ('tittle', models.CharField(default=' ', max_length=20, verbose_name='Titulo')),
                ('user', models.ForeignKey(max_length=15, on_delete=django.db.models.deletion.RESTRICT, to='user.user', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'toDo',
                'verbose_name_plural': 'toDo',
            },
        ),
    ]
