# Generated by Django 3.2.16 on 2022-12-15 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toDo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='tittle',
            field=models.CharField(default=' ', max_length=35, verbose_name='Titulo'),
        ),
    ]
