# Generated by Django 3.2.16 on 2022-12-11 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Id')),
                ('tittle', models.CharField(default=' ', max_length=20, verbose_name='Titulo')),
                ('text', models.CharField(max_length=1000, verbose_name='Texto')),
                ('type', models.PositiveIntegerField(verbose_name='Tipo')),
                ('user', models.ForeignKey(max_length=15, on_delete=django.db.models.deletion.RESTRICT, to='user.user', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Notes',
                'verbose_name_plural': 'Notes',
            },
        ),
    ]
