# Generated by Django 3.2.16 on 2022-12-04 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Id')),
                ('text', models.CharField(max_length=1000, verbose_name='Texto')),
                ('type', models.IntegerField(verbose_name='Tipo')),
                ('user', models.CharField(max_length=15, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Heroe',
                'verbose_name_plural': 'Heroes',
            },
        ),
    ]
