# Generated by Django 3.2.16 on 2022-12-04 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_options'),
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notes',
            options={'verbose_name': 'Notes', 'verbose_name_plural': 'Notes'},
        ),
        migrations.AlterField(
            model_name='notes',
            name='user',
            field=models.ForeignKey(max_length=15, on_delete=django.db.models.deletion.RESTRICT, to='user.user', verbose_name='Usuario'),
        ),
    ]
