# Generated by Django 3.2.16 on 2022-12-05 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20221203_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='tittle',
            field=models.CharField(default=' ', max_length=20, verbose_name='Texto'),
        ),
    ]
