# Generated by Django 3.2.16 on 2022-12-05 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_notes_tittle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='tittle',
            field=models.CharField(default=' ', max_length=20, verbose_name='Titulo'),
        ),
    ]
