# Generated by Django 3.2.16 on 2022-12-13 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_rename_user_id_notes_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='user',
            new_name='algo',
        ),
    ]
