# Generated by Django 3.2.16 on 2022-12-13 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_rename_user_notes_algo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='algo',
            new_name='user',
        ),
    ]
