# Generated by Django 3.2.16 on 2022-12-07 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_alter_notes_tittle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Id'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='type',
            field=models.PositiveIntegerField(verbose_name='Tipo'),
        ),
    ]
