# Generated by Django 3.2.16 on 2022-12-14 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Id')),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'toDo',
                'verbose_name_plural': 'toDo',
            },
        ),
    ]
