# Generated by Django 3.2.16 on 2022-12-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Item', '0002_item_todo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='is_active',
            new_name='checked',
        ),
        migrations.AddField(
            model_name='item',
            name='text',
            field=models.CharField(default='', max_length=500, verbose_name='Texto'),
        ),
    ]
