# Generated by Django 3.2.16 on 2022-12-11 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_bool',
            field=models.BooleanField(default=False),
        ),
    ]
