# Generated by Django 3.2.16 on 2022-12-11 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_is_active_user_is_activeted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_activeted',
            new_name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_bool',
        ),
    ]
